sudo: required
services:
  - docker

before_install:
  - docker build -t romanwhales/Dockerized-ReactApp -f Dockerfile.dev .
  
script:
  - docker run romanwhales/Dockerized-ReactApp npm run test -- --coverage